version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: cms-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: cms_db
      POSTGRES_USER: cms_user
      POSTGRES_PASSWORD: cms_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cms-network

  adminer:
    image: adminer
    container_name: cms-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - cms-network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  cms-network:
    driver: bridge 